CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "Projects" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" character varying(128) NOT NULL,
    "Name" character varying(200) NOT NULL,
    "Color" character varying(50),
    "Notes" text,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id")
);

CREATE TABLE "TodoLists" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Title" character varying(200) NOT NULL,
    "Colour_Code" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_TodoLists" PRIMARY KEY ("Id")
);

CREATE TABLE "UserProfiles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" character varying(128) NOT NULL,
    "Email" character varying(256),
    "DisplayName" character varying(200),
    "AvatarUrl" character varying(2048),
    "AutoArchiveDays" integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" character varying(128) NOT NULL,
    "ProviderKey" character varying(128) NOT NULL,
    "ProviderDisplayName" text,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" character varying(128) NOT NULL,
    "Name" character varying(128) NOT NULL,
    "Value" text,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" character varying(128) NOT NULL,
    "Title" character varying(500) NOT NULL,
    "Notes" text,
    "ProjectId" integer,
    "Archived" boolean NOT NULL,
    "SortOrder" integer NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskItems_Projects_ProjectId" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE SET NULL
);

CREATE TABLE "TodoItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ListId" integer NOT NULL,
    "Title" character varying(200) NOT NULL,
    "Note" text,
    "Priority" integer NOT NULL,
    "Reminder" timestamp with time zone,
    "Done" boolean NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_TodoItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TodoItems_TodoLists_ListId" FOREIGN KEY ("ListId") REFERENCES "TodoLists" ("Id") ON DELETE CASCADE
);

CREATE TABLE "DayMarkers" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" integer NOT NULL,
    "Date" character varying(10) NOT NULL,
    "State" character varying(20) NOT NULL,
    CONSTRAINT "PK_DayMarkers" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_DayMarkers_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskHistories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" integer NOT NULL,
    "UserId" character varying(128) NOT NULL,
    "EventType" character varying(50) NOT NULL,
    "FieldName" character varying(100),
    "OldValue" text,
    "NewValue" text,
    "CreatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_TaskHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskHistories_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);

CREATE TABLE "TaskNotes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "TaskItemId" integer NOT NULL,
    "Content" text NOT NULL,
    "Created" timestamp with time zone NOT NULL,
    "CreatedBy" text,
    "LastModified" timestamp with time zone NOT NULL,
    "LastModifiedBy" text,
    CONSTRAINT "PK_TaskNotes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_TaskNotes_TaskItems_TaskItemId" FOREIGN KEY ("TaskItemId") REFERENCES "TaskItems" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_DayMarkers_TaskItemId_Date" ON "DayMarkers" ("TaskItemId", "Date");

CREATE INDEX "IX_Projects_UserId" ON "Projects" ("UserId");

CREATE INDEX "IX_TaskHistories_TaskItemId_CreatedAt" ON "TaskHistories" ("TaskItemId", "CreatedAt");

CREATE INDEX "IX_TaskItems_ProjectId" ON "TaskItems" ("ProjectId");

CREATE INDEX "IX_TaskItems_UserId" ON "TaskItems" ("UserId");

CREATE INDEX "IX_TaskItems_UserId_Archived" ON "TaskItems" ("UserId", "Archived");

CREATE INDEX "IX_TaskNotes_TaskItemId" ON "TaskNotes" ("TaskItemId");

CREATE INDEX "IX_TodoItems_ListId" ON "TodoItems" ("ListId");

CREATE UNIQUE INDEX "IX_UserProfiles_UserId" ON "UserProfiles" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260401181704_InitialCreate', '10.0.4');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260401183807_InitialCreate2', '10.0.4');

COMMIT;

START TRANSACTION;
ALTER TABLE "AspNetUserTokens" ALTER COLUMN "Name" TYPE text;

ALTER TABLE "AspNetUserTokens" ALTER COLUMN "LoginProvider" TYPE text;

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "ProviderKey" TYPE text;

ALTER TABLE "AspNetUserLogins" ALTER COLUMN "LoginProvider" TYPE text;

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407033113_THupdate', '10.0.4');

COMMIT;

START TRANSACTION;
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260407151959_AddHiLoSequences', '10.0.4');

COMMIT;

